# Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ev-python-deployment
  labels:
    app: ev-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ev-python
  template:
    metadata:
      labels:
        app: ev-python
    spec:
      containers:
      - name: ev-python-container
        image: vignesh1718/ev-python1.1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ev-python-service
spec:
  type: LoadBalancer
  selector:
    app: ev-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ev-python-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: your-domain.com  # Replace with your domain name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ev-python-service
                port:
                  number: 80

